// not (currently) generated by UniBridge.

using System;
using System.Linq;
using UnityEngine;
using UniBridge;

public class RotFerris : MonoBehaviour {
    [SerializeField] GameObject ferris;

    private unsafe void* _rustInstance;
    
    private void Awake() {
        // ランタイムの初期化を行う
        BridgeRuntime.InitializeRuntime();
        
        // Rust側のインスタンス（RotFerris）を取得する
        unsafe {
            _rustInstance = Internal.new_ferris();
        }
    }

    private void OnDestroy() {
        unsafe {
            Internal.kill_ferris(_rustInstance);
        }
    }

    private object _InvokeRust(string name, params object[] args) {
        // Rust側のインスタンスの関数を呼び出す
        var methodName = System.Text.Encoding.UTF8.GetBytes(name);
        var args1 = args.Select(InstancePool.AppendInstance)
                       .ToArray();
        
        unsafe {
            fixed (UInt64* a = args1)
            fixed (byte* b = methodName) {
                var res = Internal.unibridge_invoke(_rustInstance,
                                                     InstancePool.AppendInstance(this), 
                                                     new Slice<char>((char*) b, (UIntPtr) methodName.Length),
                                                     new Slice<UInt64>(a, (UIntPtr) args.Length));
                var res1 = InstancePool.GetInstance(res);
                InstancePool.DisposeInstance(res);

                return res1;
            }
        }
    }

    private void Start() {
        _InvokeRust("Start", new object[] { });
    }

    private void Update() {
        _InvokeRust("Update", new object[] { });
    }

    public void SetFerrisRotation(float rot) {
        ferris.transform.rotation = Quaternion.Euler(0, 0, rot);
    }
}
