[package]
name = "unibridge-core"
version = "0.1.0"
authors = ["3c1u (Hikaru Terazono) <3c1u@vulpesgames.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"
